"""initial schema

Revision ID: 4d69047b1bb6
Revises: 
Create Date: 2026-09-14 04:37:57.563378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d69047b1bb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('corpus_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celex', sa.String(), nullable=False),
    sa.Column('eli', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('consolidated_date', sa.Date(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celex')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('corpus_version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('corpus_version_id', sa.Integer(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('triggering_article', sa.String(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('row_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_version_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.String(), nullable=False),
    sa.Column('eid', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('amendment_marker', sa.String(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['provision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corpus_version_id', 'citation_id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_version_id', sa.Integer(), nullable=False),
    sa.Column('provision_id', sa.Integer(), nullable=False),
    sa.Column('parent_provision_id', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('index_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.ForeignKeyConstraint(['parent_provision_id'], ['provision.id'], ),
    sa.ForeignKeyConstraint(['provision_id'], ['provision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provision_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_version_id', sa.Integer(), nullable=False),
    sa.Column('from_provision_id', sa.Integer(), nullable=False),
    sa.Column('to_citation_id', sa.String(), nullable=False),
    sa.Column('to_provision_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.ForeignKeyConstraint(['from_provision_id'], ['provision.id'], ),
    sa.ForeignKeyConstraint(['to_provision_id'], ['provision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('provision_citation_id', sa.String(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citation')
    op.drop_table('provision_reference')
    op.drop_table('message')
    op.drop_table('chunk')
    op.drop_table('provision')
    op.drop_table('classification_run')
    op.drop_table('chat_session')
    op.drop_table('corpus_version')
    op.drop_table('app_user')
    # ### end Alembic commands ###
