"""add query_trace and retrieval_trace tables

Revision ID: d0522492c752
Revises: f6676fdebaf8
Create Date: 2026-09-19 01:50:19.890461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0522492c752'
down_revision: Union[str, None] = 'f6676fdebaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_trace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('corpus_version_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('retrieval_config', sa.String(), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=False),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_trace_created_at', 'query_trace', ['created_at'], unique=False)
    op.create_table('retrieval_trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_trace_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('provision_citation_id', sa.String(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=False),
    sa.Column('rrf_score', sa.Float(), nullable=True),
    sa.Column('vector_rank', sa.Integer(), nullable=True),
    sa.Column('lexical_rank', sa.Integer(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('used_in_context', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.ForeignKeyConstraint(['query_trace_id'], ['query_trace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_trace_query_trace_id', 'retrieval_trace', ['query_trace_id'], unique=False)
    # NOTE: autogenerate also proposed dropping chunk_embedding_hnsw_idx and
    # chunk_fts_idx here - a false positive. Those indexes were added by hand
    # (op.execute) in a prior migration, never declared as SQLAlchemy Index()
    # objects on the Chunk model, so autogenerate sees "DB has it, model
    # doesn't know about it" and wrongly concludes it should be removed.
    # Deliberately omitted - this migration is additive only.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retrieval_trace_query_trace_id', table_name='retrieval_trace')
    op.drop_table('retrieval_trace')
    op.drop_index('ix_query_trace_created_at', table_name='query_trace')
    op.drop_table('query_trace')
    # ### end Alembic commands ###
